server:
  port: 8801
spring:
  application:
    name: service-user
  # Default active profile
  profiles:
    active: dev
  rabbitmq:
    host: 106.52.132.48
    port: 5672
    virtual-host: my_vhost
    username: admin
    password: admin

  # mongoDB
  data:
    mongodb:
      uri: mongodb://admin:123456@106.52.132.48:27017/pig

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.52.132.48:3306/sb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: just4fun