#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 106.52.132.48:8848

# 日志配置
logging:
  level:
    # 指定路径配置log级别
    com:
      example: debug
  file:
    name: F:\log\user-service.log

