spring:
  cloud:
    nacos:
      discovery:
        server-addr: 106.52.132.48:8848

# 日志配置
logging:
  level:
    # 指定路径配置log级别
    com:
      example: info
  file:
    name: /opt/jar/springcloud/log/user-service.log

