eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8801
spring:
  application:
    name: service-user

  # mongoDB
  data:
    mongodb:
      uri: mongodb://admin:123456@106.52.132.48:27017/pig

# 日志配置
logging:
  level:
    # 指定路径配置log级别
    com:
      example: debug
  file:
    name: F:\log\user-service.log

