eureka:
  client:
    serviceUrl:
      defaultZone: http://106.52.132.48:8761/eureka/

# 日志配置
logging:
  level:
    # 指定路径配置log级别
    com:
      example: info
  file:
    name: /opt/jar/springcloud/log/user-service.log

