spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    # sentinel
    sentinel:
      transport:
        port: 18763
        dashboard: localhost:8748
  # redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password: #ENC(VPSapwY1AJzmHZQjWq62KpBiMDu7W37M)
    timeout: 60000
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000
        max-idle: 30
        min-idle: 10

# 日志配置
logging:
  level:
    # 指定路径配置log级别
    com:
      alibaba:
        nacos:
          client:
            naming: error
      example: debug
  file:
    name: F:\log\web-service.log

login-interceptor: false