#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://106.52.132.48:8761/eureka/

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 106.52.132.48:8848
  # redis
  redis:
    database: 0
    host: 106.52.132.48
    port: 6379
    password: ENC(VPSapwY1AJzmHZQjWq62KpBiMDu7W37M)
    timeout: 60000
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000
        max-idle: 30
        min-idle: 10

# 日志配置
logging:
  level:
    # 指定路径配置log级别
    com:
      example: info
  file:
    name: /opt/jar/springcloud/log/web-service.log


login-interceptor: false