server:
  port: 8901
spring:
  application:
    name: customer-web
  # Mvc
  mvc:
    static-path-pattern: /**
    view:
      suffix: .html
      prefix: /
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/


  # Default active profile
  profiles:
    active: dev
  # rabbitmq
  rabbitmq:
    host: 106.52.132.48
    port: 5672
    virtual-host: my_vhost
    username: admin
    password: admin

  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster:
        nodes: 106.52.132.48:9300
        name: docker-cluster

# ribbon的超时时间
#service-user:
#  ribbon:
#    ConnectTimeout: 3000
#    ReadTimeout: 3000
#    MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
#    MaxAutoRetriesNextServer: 0 #重试负载均衡其他的实例最大重试次数,不包括首次调用
#    OkToRetryOnAllOperations: false  #是否所有操作都重试 ,设置为false时，只会对get请求进行重试

#如果设置为true，便会对所有的请求进行重试，如果是put或post等写操作，
#如果服务器接口没做幂等性，会产生不好的结果，所以OkToRetryOnAllOperations慎用。

#feign的配置，连接超时及读取超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
#  hystrix:
#    enabled: true
  sentinel:
    enabled: true

# 加密的盐
jasypt:
  encryptor:
    password: just4fun

# des算法的key
des:
  key: 12345678

# 线程参数
task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

